spring:
  webflux:
    hidden-method:
      filter:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: weblflux
      uri: mongodb://localhost:27017/webflux

